"""Add sistema de cashback

Revision ID: 492878ad0e52
Revises: 7d5b79e0a2ae
Create Date: 2026-04-14 16:54:47.170305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492878ad0e52'
down_revision = '7d5b79e0a2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_cashback', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('saldo_cashback')

    # ### end Alembic commands ###
