"""Removendo colunas fiscais para simplificar MVP

Revision ID: 5d5ed917fee6
Revises: a63a7ba36e8c
Create Date: 2026-04-13 16:28:19.549368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5ed917fee6'
down_revision = 'a63a7ba36e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.drop_column('ambiente_nfe')
        batch_op.drop_column('ie')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('caminho_certificado')
        batch_op.drop_column('senha_certificado')

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('cfop')
        batch_op.drop_column('cest')
        batch_op.drop_column('ncm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ncm', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cest', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cfop', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_certificado', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('caminho_certificado', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ie', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('ambiente_nfe', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
