"""Adicionando telefone e plano na Loja para Landing Page

Revision ID: 7d5b79e0a2ae
Revises: 5d5ed917fee6
Create Date: 2026-04-13 17:14:33.435016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5b79e0a2ae'
down_revision = '5d5ed917fee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plano', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.drop_column('plano')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
