"""Adicionando colunas NCM e CFOP no Produto

Revision ID: a63a7ba36e8c
Revises: df0031f148b4
Create Date: 2026-04-11 02:44:48.453741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63a7ba36e8c'
down_revision = 'df0031f148b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ncm', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cfop', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cest', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('cest')
        batch_op.drop_column('cfop')
        batch_op.drop_column('ncm')

    # ### end Alembic commands ###
