"""Adicionando colunas fiscais na tabela Loja

Revision ID: df0031f148b4
Revises: 
Create Date: 2026-04-11 00:01:23.380216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0031f148b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ie', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('caminho_certificado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('senha_certificado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ambiente_nfe', sa.String(length=20), nullable=True))
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('ambiente_nfe')
        batch_op.drop_column('senha_certificado')
        batch_op.drop_column('caminho_certificado')
        batch_op.drop_column('ie')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
